### ISSUE TITLE
Epic: Visualize pipelines in Grafana

### ISSUE THREAD

**Issue by kminehart** [grafana/scribe#2]
Because every pipeline step is executed in Go, we can wrap pipelines and steps in metrics and metadata collection and track step duration and errors.

Pipelines are short-lived programs and aren't exactly scrapable by prometheus without some kind of push gateway.

#### Logs

Tasks:
* [x] Decide: Do we need detailed logs for successful builds? (yes we do)
* [x] We need a more standardized logging format.
* [x] Get logs into Loki from local pipeline executions.
* [x] Get logs into Loki from Drone / remote pipeline executions.

#### Visualizations

Tasks:
* [x] Grafana Panel(s) for a pipeline graph. Does a nodegraph work here?
    * It doesn't yet, but it totally could.
