### ISSUE TITLE
Epic: Formatted logging

### ISSUE THREAD

**Issue by kminehart** [grafana/scribe#6]
* [x] Update `plog` package to use a formatted logger. (Logrus?)
* [x] Log all standard output of steps.
* [x] How do we get this into loki?
